### ISSUE TITLE
It doesn't understand network paths

### ISSUE THREAD

**Issue by ElgarL** [Tenpi/Crunchyroll-Downloader#85]
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/a730b595-5a7a-4f70-a9ad-5bea86c36bd0)

![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/f9d6b735-08e1-4fd7-9de8-f37f55a93ea7)
It fails to save the file as the path used is incorrect. It instead saves to the root.

**Comment by Tenpi** [comment]
Tell me if it's fixed in 0.7.4

**Comment by ElgarL** [comment]
Afraid it's not fixed (tested on Win 10).

> renderer.js:43 Error: No resource with given identifier found
> t @ renderer.js:43
> renderer.js:43 [error] \\\\DROBO5N/Public/Anime Downloads/One Piece/One Piece East Blue (1 61)/E1 - I’m Luffy! The Man Who’s Gonna Be King of the Pirates!.ass: No such file or directory
> t @ renderer.js:43
> renderer.js:43 Error: FFmpeg exited with code 1
>     at s (C:\Program Files\Crunchyroll Downloader\resources\app.asar\dist\main.js:28:22026)
>     at ChildProcess.o (C:\Program Files\Crunchyroll Downloader\resources\app.asar\dist\main.js:28:22253)
>     at ChildProcess.emit (node:events:525:35)
>     at ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by Tenpi** [comment]
It was mainly a blind fix because I don't use network drives, does it have permission to write to it? Maybe you have to assign it a drive letter so it can see it (guide here): https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d 

Alternatively you can make a symlink locally that points to a folder in the network drive that should work too.

**Comment by ElgarL** [comment]
It has permissions, mapped drives is no use.

You can easily test it yourself sharing any folder then using \\localhost\share

**Comment by ElgarL** [comment]
0.7.5 correctly creates the folders at the UNC path, and saves teh .ass and starts to create the .mp4 however, it errors. I think you missed an escape somewhere.
![image](https://github.com/Tenpi/Crunchyroll-Downloader/assets/898636/c1516384-4436-4f74-9a46-573b393e5ee6)

**Comment by Tenpi** [comment]
This is probably fixed in 0.7.6
